'use strict';
/* Word timings [start,end] in seconds, generated from each narration recording. */
const moonlightWordTimes=[[[0.0,0.22],[0.22,0.52],[0.52,1.04],[1.68,1.82],[1.82,2.12],[2.12,2.22],[2.22,2.52],[2.52,2.88],[2.88,3.2],[3.2,3.58],[3.58,3.68],[3.68,3.96]],[[0.0,0.26],[0.8,1.28],[1.28,1.42],[1.42,1.54],[1.54,1.78],[1.78,2.12],[3.42,3.46],[3.46,3.58],[3.58,3.72],[3.72,4.2],[4.2,4.62],[4.62,4.94],[4.94,5.22]],[[0.0,0.32],[0.32,0.66],[0.66,0.9],[0.9,1.08],[2.3,2.3],[2.64,2.82],[2.82,3.1],[3.1,3.46],[3.46,3.62],[3.62,3.98],[3.98,4.38]],[[0.0,0.18],[0.18,0.44],[0.44,1.16],[1.16,1.4],[1.4,1.78],[1.78,2.38],[2.38,2.68],[2.68,2.98],[2.98,3.18],[3.18,3.56],[3.56,3.94]],[[0.0,0.18],[0.18,0.38],[0.38,1.08],[1.08,1.26],[1.26,1.38],[1.38,1.66],[1.66,2.02],[2.02,2.16],[2.16,2.4],[2.4,2.8]],[[0.0,0.2],[0.46,0.54],[0.74,0.96],[0.96,1.16],[1.16,1.5],[1.5,2.02],[2.02,2.2],[2.2,2.44],[2.44,2.88],[2.88,3.36],[3.36,3.72]],[[0.0,0.14],[0.14,0.3],[0.3,0.6],[0.6,1.08],[1.68,1.82],[1.82,1.94],[1.94,2.12],[2.12,2.42],[2.42,2.8],[2.8,3.0],[3.0,3.24],[3.24,3.68],[3.68,4.02],[4.02,4.34]],[[0.0,0.28],[0.64,0.94],[0.94,1.28],[1.28,1.64],[1.64,2.34],[2.84,2.96],[2.96,3.18],[3.18,3.6],[3.6,4.14],[4.14,4.54],[4.54,4.8]],[[0.0,0.24],[0.24,0.48],[0.48,0.78],[2.08,2.1],[2.1,2.32],[2.32,2.58],[2.58,2.88],[2.88,3.18],[3.64,4.12],[4.12,4.46],[4.46,4.8],[4.8,5.62],[5.62,5.84],[5.84,6.12],[6.12,6.72],[6.72,7.02],[7.02,7.24]]];
window.MoonlightStory={
 id:'glup-moonlight-wish',title:'Glup and the Moonlight Wish',music:encodeURI('audio/read aloud moonlight wish/moonlight-music-soft.mp3'),format:'read-along',theme:'moonlight',
 scenes:[
  {id:'light',title:'A Little Light',text:'One quiet night, Glup saw a tiny light shining in the grass.',description:'Glup discovers a tiny glowing star on the grass beneath a quiet night sky.',talk:{who:'glup',line:'glup1'}},
  {id:'lost',title:'A Lost Star',text:'Oh! It was a little star. And it was very far from home.',description:'Glup looks gently at a sad little star that has fallen from the sky.',talk:{who:'star',line:'star2'}},
  {id:'forest',title:'Into the Forest',text:'Glup promised to help. Together, they walked through the moonlit forest.',description:'Glup carries the little star along a winding path between soft moonlit trees.',talk:{who:'glup',line:'glup3'}},
  {id:'firefly',title:'The Firefly',text:'A tiny firefly joined them and showed them the brightest path.',description:'A friendly glowing firefly lights the forest path for Glup and the star.',talk:{who:'star',line:'star4'}},
  {id:'lake',title:'Across the Lake',text:'The moon sparkled on the water like a silver road.',description:'Glup and the little star stand at a calm lake with a silver reflection of the moon.',talk:{who:'moon',line:'moon5'}},
  {id:'hill',title:'Up the Hill',text:'Up, up, up they climbed until the stars seemed very close.',description:'Glup carries the little star up a gentle grassy hill toward the night sky.',talk:{who:'glup',line:'gluo6'}},
  {id:'moon',title:'The Moon Helps',text:'The moon smiled down, and the little star began to shine brighter than ever.',description:'A smiling moon shines on Glup and the little star, which glows with warm golden light.',talk:{who:'star',line:'star7'}},
  {id:'home',title:'Back Home',text:'Then, with one bright sparkle, the little star floated back home.',description:'Glup watches the little star float up from the hill into the sky.',talk:{who:'glup',line:'glup8'}},
  {id:'goodnight',title:'Goodnight, Little Star',text:'Glup waved goodbye. And every night after that, one little star seemed to shine just for him.',description:'Glup rests on the hill looking up at his little star shining beside the moon.'}
 ].map((scene,i)=>({...scene,audioNarration:encodeURI(`audio/read aloud moonlight wish/${i+1}.mp3`),wordTimes:moonlightWordTimes[i],talkAudio:scene.talk?encodeURI(`audio/read aloud moonlight wish/${scene.talk.line}.mp3`):null}))
};

/* Non-interactive illustrations: the existing Glup sprite stays unchanged. */
window.MoonlightArt=(()=>{
 const star=(sad=false)=>`<svg viewBox="0 0 120 120" aria-hidden="true"><path fill="#ffdf83" stroke="#fff0b3" stroke-width="3" stroke-linejoin="round" d="M60 10Q64 10 68 21L78 40 102 44Q114 45 105 55L88 72 91 97Q93 109 81 103L60 92 38 103Q27 109 29 97L33 72 15 55Q6 45 18 44L42 40 53 18Q57 10 60 10Z"/><ellipse cx="45" cy="61" rx="4" ry="5" fill="#405165"/><ellipse cx="75" cy="61" rx="4" ry="5" fill="#405165"/><path d="${sad?'M51 79Q60 69 69 79':'M51 74Q60 85 69 74'}" fill="none" stroke="#405165" stroke-width="3" stroke-linecap="round"/><ellipse cx="37" cy="71" rx="6" ry="3" fill="#f4a795" opacity=".6"/><ellipse cx="83" cy="71" rx="6" ry="3" fill="#f4a795" opacity=".6"/></svg>`;
 const moon=`<svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="49" fill="#fff1ca"/><circle cx="36" cy="35" r="9" fill="#e7dcb8" opacity=".45"/><circle cx="83" cy="40" r="6" fill="#e7dcb8" opacity=".4"/><path d="M37 61q6-7 12 0m22 0q6-7 12 0M49 76q11 11 22 0" stroke="#7e8588" fill="none" stroke-width="3" stroke-linecap="round"/></svg>`;
 const trees=`<svg class="moon-trees" viewBox="0 0 1000 480" preserveAspectRatio="none" aria-hidden="true"><g fill="#284b61"><path d="M58 420V154h12v266M189 400V90h14v310M889 411V111h13v300M966 440V181h13v259"/><ellipse cx="65" cy="175" rx="84" ry="140"/><ellipse cx="195" cy="123" rx="70" ry="115"/><ellipse cx="892" cy="145" rx="77" ry="139"/><ellipse cx="980" cy="220" rx="70" ry="120"/></g><g fill="#375f70"><ellipse cx="30" cy="230" rx="52" ry="97"/><ellipse cx="154" cy="151" rx="35" ry="67"/><ellipse cx="931" cy="204" rx="38" ry="100"/></g></svg>`;
 function scene(scene){return `<div class="moon-scene moon-${scene.id}" role="img" aria-label="${scene.description}"><div class="moon-sky-stars" aria-hidden="true">${[[8,14],[19,31],[30,12],[45,24],[58,10],[67,33],[84,19],[93,39],[38,42]].map(([x,y],i)=>`<i style="left:${x}%;top:${y}%;--delay:${i*.6}s">${i%3?'·':'✧'}</i>`).join('')}</div>${scene.talk?.who==='moon'?`<button class="moon-disc talk-button" data-read-action="talk" aria-label="Tap the moon to hear what it says">${moon}<span class="talk-hint" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 4v14M5 12l7 7 7-7"/></svg></span></button>`:`<div class="moon-disc">${moon}</div>`}<div class="moon-cloud" aria-hidden="true"></div><div class="moon-distant-hill" aria-hidden="true"></div>${['forest','firefly'].includes(scene.id)?trees:''}<div class="moon-water-surface" aria-hidden="true"><span></span><span></span><span></span></div><div class="moon-ground" aria-hidden="true"></div><div class="moon-path" aria-hidden="true"></div>${scene.talk?.who==='glup'?'<button class="story-glup moon-glup talk-button" style="--x:0%;--y:100%" data-read-action="talk" aria-label="Tap Glup to hear what he says"><span class=\"talk-hint\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 4v14M5 12l7 7 7-7\"/></svg></span></button>':'<span class="story-glup moon-glup" style="--x:0%;--y:100%" aria-hidden="true"></span>'}${scene.talk?.who==='star'?`<button class="moon-little-star talk-button" data-read-action="talk" aria-label="Tap the little star to hear what it says">${star(scene.id==='lost')}<span class="talk-hint" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 4v14M5 12l7 7 7-7"/></svg></span></button>`:`<span class="moon-little-star">${star(scene.id==='lost')}</span>`}${scene.id==='firefly'?'<span class="moon-firefly" aria-hidden="true"><i></i></span>':''}<div class="moon-foreground" aria-hidden="true"></div></div>`;}
 return {star,scene};
})();

window.ReadAlongPlayer=(()=>{
 let root=null,book=null,page=0,onHome=null,events=null,narration=null,talkVoice=null,music=null,started=false,wordFrame=0;
 const speaker='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h4l5-4v14l-5-4H4zM17 8q5 4 0 8M20 5q7 7 0 14"/></svg>';
 function stopNarration(){cancelAnimationFrame(wordFrame);if(narration){narration.pause();narration=null;}if(talkVoice){talkVoice.pause();talkVoice=null;}highlight(-1);}
 function talkHint(show){root?.querySelector('.talk-button')?.classList.toggle('talk-ready',show);}
 function playTalk(){const src=book.scenes[page].talkAudio;if(!src)return;stopNarration();talkHint(false);const talk=root.querySelector('.talk-button');talk?.classList.remove('talk-speaking');void talk?.offsetWidth;talk?.classList.add('talk-speaking');talkVoice=new Audio(src);talkVoice.play().catch(()=>{});}
 function highlight(index){root?.querySelectorAll('.read-word').forEach((word,i)=>word.classList.toggle('reading',i===index));}
 function followWords(audio,times){const tick=()=>{if(audio!==narration)return;const now=audio.currentTime;let index=-1;for(let i=0;i<times.length;i++){if(times[i][0]<=now)index=i;else break;}if(index>=0&&now>times[index][1]+.3)index=-1;highlight(audio.ended?-1:index);if(!audio.ended)wordFrame=requestAnimationFrame(tick);};wordFrame=requestAnimationFrame(tick);}
 function words(scene){const list=scene.text.split(' ');if(!scene.wordTimes||scene.wordTimes.length!==list.length)return scene.text;return list.map(word=>`<span class="read-word">${word}</span>`).join(' ');}
 function playNarration(){const src=book.scenes[page].audioNarration;if(!src)return;stopNarration();narration=new Audio(src);const audio=narration,times=book.scenes[page].wordTimes;talkHint(false);if(times)followWords(audio,times);audio.addEventListener('ended',()=>{if(audio===narration)talkHint(true);});narration.play().catch(()=>{});}
 function narrationButton(){return started?'<button class="narration-button" data-read-action="narration"><span aria-hidden="true">↻</span> Repeat</button>':'<button class="narration-button narration-start" data-read-action="start"><span aria-hidden="true">▶</span> Start</button>';}
 function soundOn(){try{return localStorage.getItem('mini-playroom-sound')!=='off';}catch{return true;}}
 // The music file is already attenuated (~19 dB); do not rely on media volume on iOS.
 function startMusic(){stopMusic();if(!book.music||!soundOn())return;music=new Audio(book.music);music.loop=true;music.play().catch(()=>{});}
 function stopMusic(){if(music){music.pause();music=null;}}
 document.addEventListener('visibilitychange',()=>{if(!music)return;if(document.hidden)music.pause();else music.play().catch(()=>{});});
 function close(){stopNarration();stopMusic();events?.abort();events=null;root=null;}
 function open(element,home,entry){close();root=element;onHome=home;book=entry;page=0;started=false;startMusic();events=new AbortController();root.addEventListener('click',handle,{signal:events.signal});render();}
 function render(){stopNarration();if(page>0)started=true;const scene=book.scenes[page],last=page===book.scenes.length-1;
  root.innerHTML=`<article class="storybook readalong-book" aria-labelledby="readalong-title"><nav class="story-toolbar" aria-label="Story controls"><button class="book-home" data-read-action="home" aria-label="Back to Stories">⌂<span>Stories</span></button><span class="story-book-name">${book.title}</span></nav><div class="readalong-page page-arrival">${window.MoonlightArt.scene(scene)}<div class="readalong-copy"><h1 id="readalong-title">${scene.title}</h1><p>${words(scene)}</p>${scene.audioNarration?narrationButton():''}</div></div><nav class="book-pager" aria-label="Book pages"><button class="page-arrow" data-read-action="back" aria-label="Back" ${page===0?'disabled':''}>‹</button><span class="story-page-number" aria-live="polite">${page+1} / ${book.scenes.length}</span>${last?'<div class="readalong-ending"><button class="readalong-again" data-read-action="restart"><span aria-hidden="true">↻</span> Read Again</button><button class="book-home" data-read-action="home" aria-label="Back to Stories">⌂<span>Back to Stories</span></button></div>':'<button class="page-arrow" data-read-action="next" aria-label="Next">›</button>'}</nav></article>`;
  root.querySelector('h1').setAttribute('tabindex','-1');root.querySelector('h1').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});
  if(started&&soundOn())playNarration();
 }
 function handle(event){const button=event.target.closest('[data-read-action]');if(!button||button.disabled)return;switch(button.dataset.readAction){case 'home':onHome();break;case 'back':if(page>0){page--;render();}break;case 'next':if(page<book.scenes.length-1){page++;render();}break;case 'restart':page=0;render();break;case 'start':started=true;button.outerHTML=narrationButton();playNarration();break;case 'narration':playNarration();break;case 'talk':playTalk();break;}}
 return {open,close};
})();
